version: '3.8'

# Services: postgres
services:
  db:
    image: postgres
    container_name: postgres_ISA
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: Champagne_Shop
      PGADMIN_LISTEN_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    networks:
      - rete_ISA

  pgadmin:
    image: dpage/pgadmin4:4.23
    container_name: pgadmin_ISA
    environment:
        PGADMIN_DEFAULT_EMAIL: ion.boleac2@gmail.com
        PGADMIN_DEFAULT_PASSWORD: qwe
        PGADMIN_LISTEN_PORT: 80
    volumes:
        - pgadmin:/var/lib/pgadmin
    ports:
        - "50000:80"
    
    depends_on:
        - db
    networks:
        - rete_ISA

  app:
    container_name: app_ISA
    depends_on:
      - db
    build: .
    environment:
      - DATABASE_HOST = db
      - DATABASE_USERNAME = root
      - DATABASE_PASSWORD = qwe
      - DATABASE_NAME = Champagne_Shop
      - LOGFILE = /var/log/service.log
    ports:
      - "8080:8080"
      - "4848:4848"
    # For interactive debugging (open a shell in the container)
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - rete_ISA


# Volumes
volumes:
  postgres_data:
  pgadmin:

# Networks
networks:
  rete_ISA:
    name: rete_ISA
    driver: bridge