version: '3.8'

# Services: postgres
services:
  db:
    image: postgres
    container_name: postgres_ISA
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: Champagne_Shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/backup.sql:/docker-entrypoint-initdb.d/backup.sql
    ports:
      - "5432:5432"
    networks:
      - rete_ISA


  app:
    image: iuon/champagne_shop-app:1.1.3
    container_name: app_ISA
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080" # GlassFish HTTP
      - "4848:4848" # GlassFish Admin
    # For interactive debugging (open a shell in the container)
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - rete_ISA


# Volumes
volumes:
  postgres_data:
  pgadmin:

# Networks
networks:
  rete_ISA:
    name: rete_ISA
    driver: bridge
