# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Docker compose up, test and push to Docker Hub

on:
  release:
    types: [published]
  push:
    branches: [ "testCICD" ]
  pull_request:
    branches: [ "testCICD" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}
          username: iuon
          password: fnWY%!56KuxtvJMD
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: iuon/champagne_shop-app
      
      - name: Build and push Docker image
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: docker-compose.yml
        env:
          DATABASE_NAME: Champagne_Shop
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: qwe
          DATABASE_HOST: localhost

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: list Docker image
        run: docker image list
      - name: list Docker container
        run: docker container list

      - name: tag container
        run: docker tag champagne_shop_app:latest iuon/champagne_shop-app:1.1.2

      - name: push container
        run: docker push iuon/champagne_shop-app:1.1.2
